#include <metal_stdlib>
using namespace metal;

// Trimmed MIDI-only telemetry kernel for anisotropic: one TelemetryCell per low-res
// ray (geometry stats + 4x4 cells + full-res centroid derive from this buffer on
// the CPU). No sonification wavetable/orbit-trajectory/field-scan buffers.
// GENERATED by tools/build_midi_telemetry.py from anisotropic_raymarch.metal — the
// FoldParams struct and DE region below are lifted verbatim. Do not hand-edit;
// re-run the generator if the DE changes.

struct TelemetryParams {
    int   gridWidth;
    int   gridHeight;
    int   pad0;
    int   pad1;
    float4 camPos;
    float4 camForward;
    float4 camRight;
    float4 camUp;
    float4 tanFov;
    float4 march;
    int   maxSteps;
    int   pad2;
    int   pad3;
    int   pad4;
};

struct TelemetryCell {
    int   hit;
    int   steps;
    float depth;
    float pad;
    float4 normal;
    float4 trap;
};

struct FoldParams {
    int iterations; int mode; int juliaMode; int pad0;
    float4 boxParams;  // (scale, rx, ry, rz)
    float4 surfParams; // (foldLimit, shearZ, shearY, bailout)
    float4 juliaC;     // (cx, cy, cz, _)
    float4 rot;        // (_, _, _, fudge)
    float4 boundSphere;
};

// ===== DE region lifted verbatim from anisotropic_raymarch.metal =====
// delta-DE step (no global const - inlined below)

float3x3 anisoBuildM(constant FoldParams& fp) {
    float scale = fp.boxParams.x;
    float3 ratio = fp.boxParams.yzw;
    float cz=cos(fp.surfParams.y), sz=sin(fp.surfParams.y);
    float cy=cos(fp.surfParams.z), sy=sin(fp.surfParams.z);
    float3x3 Rz = float3x3(float3(cz,sz,0), float3(-sz,cz,0), float3(0,0,1));
    float3x3 Ry = float3x3(float3(cy,0,-sy), float3(0,1,0), float3(sy,0,cy));
    float3x3 S  = float3x3(float3(scale*ratio.x,0,0), float3(0,scale*ratio.y,0), float3(0,0,scale*ratio.z));
    return Rz * Ry * S;
}

float3 anisoBoxFold(float3 z, float L) { return clamp(z, -L, L) * 2.0f - z; }

float3 anisoRunFixed(float3 p0, int n, float3x3 M, float L, bool julia, float3 jc) {
    float3 z = p0;
    float3 c = julia ? jc : p0;
    for (int i = 0; i < n; i++) z = M * anisoBoxFold(z, L) + c;
    return z;
}

float aniseSigmaMax(float3x3 J) {
    float3x3 A = transpose(J) * J;
    float3 v = normalize(float3(0.71f, 0.53f, 0.46f));
    for (int k = 0; k < 10; k++) {
        float3 Av = A * v;
        float m = max(max(abs(Av.x), abs(Av.y)), abs(Av.z));
        v = (m > 1e-20f) ? Av/m : v;
        v = normalize(v);
    }
    return sqrt(max(dot(v, A*v), 0.0f));
}

float estimateFull(float3 p, constant FoldParams& fp, thread float4& outTrap) {
    float3x3 M = anisoBuildM(fp);
    float L = fp.surfParams.x, bailout = fp.surfParams.w;
    bool julia = (fp.juliaMode == 1);
    float3 jc = fp.juliaC.xyz;
    float3 z = p, c = julia ? jc : p;
    int N = fp.iterations;
    outTrap = float4(1e20f);

    for (int i = 0; i < fp.iterations; i++) {
        if (length(z) > bailout) { N = i; break; }
        z = M * anisoBoxFold(z, L) + c;
        float rz = length(z);
        outTrap.x = min(outTrap.x, rz);
        outTrap.y = min(outTrap.y, abs(z.x));
        outTrap.z = min(outTrap.z, length(z.xy));
        outTrap.w = min(outTrap.w, abs(rz - 1.0f));
    }
    float3 zb = z;

    float3 zx = anisoRunFixed(p + float3(1e-4f, 0, 0), N, M, L, julia, jc);
    float3 zy = anisoRunFixed(p + float3(0, 1e-4f, 0), N, M, L, julia, jc);
    float3 zz = anisoRunFixed(p + float3(0, 0, 1e-4f), N, M, L, julia, jc);

    float3x3 J = float3x3((zx-zb)/1e-4f, (zy-zb)/1e-4f, (zz-zb)/1e-4f);
    float norm;
    if (fp.mode == 1) norm = aniseSigmaMax(J);
    else norm = sqrt(dot(J[0],J[0]) + dot(J[1],J[1]) + dot(J[2],J[2]));
    return length(zb) / max(norm, 1e-12f);
}


float estimate(float3 p, constant FoldParams& fp) {
    float4 dummy;
    return estimateFull(p, fp, dummy);
}

bool intersectSphereForward(float3 ro, float3 rd, float3 center, float radius, thread float& tOut) {
    float3 oc = ro - center;
    float b = dot(oc, rd);
    float c = dot(oc, oc) - radius * radius;
    if (c <= 0.0f) { tOut = 0.0f; return true; }
    float disc = b * b - c;
    if (disc < 0.0f) { tOut = 0.0f; return false; }
    float sq = sqrt(disc);
    float t0 = -b - sq;
    if (t0 >= 0.0f) { tOut = t0; return true; }
    float t1 = -b + sq;
    if (t1 >= 0.0f) { tOut = t1; return true; }
    tOut = 0.0f;
    return false;
}

// ============================================================================
// Telemetry kernel — 64x36 low-res re-march, one TelemetryCell per ray
// ============================================================================

kernel void anisotropic_telemetry(
    constant FoldParams&      fp    [[buffer(0)]],
    constant TelemetryParams& tp    [[buffer(1)]],
    device   TelemetryCell*   cells [[buffer(2)]],
    uint2 gid [[thread_position_in_grid]])
{
    int px = int(gid.x);
    int py = int(gid.y);
    if (px >= tp.gridWidth || py >= tp.gridHeight) return;

    int idx = py * tp.gridWidth + px;

    float u = (float(px) + 0.5f) / float(tp.gridWidth);
    float v = 1.0f - (float(py) + 0.5f) / float(tp.gridHeight);
    float x = (2.0f * u - 1.0f) * tp.tanFov.x;
    float y = (2.0f * v - 1.0f) * tp.tanFov.y;
    float3 ro = tp.camPos.xyz;
    float3 rd = normalize(tp.camForward.xyz + x * tp.camRight.xyz + y * tp.camUp.xyz);

    float hitEps   = tp.march.x;
    float maxDist  = tp.march.y;
    float normEps  = tp.march.z;
    int   maxSteps = tp.maxSteps;
    float fudge    = fp.rot.w;

    TelemetryCell cell;
    cell.pad = 0.0f;

    float tEnter;
    if (!intersectSphereForward(ro, rd, fp.boundSphere.xyz, fp.boundSphere.w, tEnter)) {
        cell.hit = 0; cell.steps = 0; cell.depth = maxDist;
        cell.normal = float4(0.0f); cell.trap = float4(0.0f);
        cells[idx] = cell;
        return;
    }

    float t = max(0.0f, tEnter);
    bool  didHit = false;
    int   i = 0;

    for (i = 0; i < maxSteps; i++) {
        float3 p = ro + rd * t;
        float d = estimate(p, fp) * fudge;
        if (d < hitEps) { didHit = true; break; }
        t += d;
        if (t > maxDist) break;
    }

    if (!didHit) {
        cell.hit = 0; cell.steps = i; cell.depth = maxDist;
        cell.normal = float4(0.0f); cell.trap = float4(0.0f);
        cells[idx] = cell;
        return;
    }

    float3 hitPoint = ro + rd * t;

    float4 trap;
    estimateFull(hitPoint, fp, trap);

    float2 k = float2(1.0f, -1.0f);
    float3 n =
        k.xyy * estimate(hitPoint + k.xyy * normEps, fp) +
        k.yyx * estimate(hitPoint + k.yyx * normEps, fp) +
        k.yxy * estimate(hitPoint + k.yxy * normEps, fp) +
        k.xxx * estimate(hitPoint + k.xxx * normEps, fp);
    float nLen = length(n);
    float3 normal = (nLen > 1e-6f) ? n / nLen : float3(0.0f);

    cell.hit = 1; cell.steps = i; cell.depth = t;
    cell.normal = float4(normal, 0.0f); cell.trap = trap;
    cells[idx] = cell;
}
