#include <metal_stdlib>
using namespace metal;

// Trimmed MIDI-only telemetry kernel for pseudokleinian4d: one TelemetryCell per low-res
// ray (geometry stats + 4x4 cells + full-res centroid derive from this buffer on
// the CPU). No sonification wavetable/orbit-trajectory/field-scan buffers.
// GENERATED by tools/build_midi_telemetry.py from pseudokleinian4d_raymarch.metal — the
// FoldParams struct and DE region below are lifted verbatim. Do not hand-edit;
// re-run the generator if the DE changes.

struct TelemetryParams {
    int   gridWidth;
    int   gridHeight;
    int   pad0;
    int   pad1;
    float4 camPos;
    float4 camForward;
    float4 camRight;
    float4 camUp;
    float4 tanFov;
    float4 march;
    int   maxSteps;
    int   pad2;
    int   pad3;
    int   pad4;
};

struct TelemetryCell {
    int   hit;
    int   steps;
    float depth;
    float pad;
    float4 normal;
    float4 trap;
};

struct FoldParams {
    int iterations; int mode; int juliaMode; int pad0;
    float4 boxParams;  // (cSizeX, cSizeY, cSizeZ, sphereFoldScale)
    float4 surfParams; // (tubeRadius, deOffset, deTweak, sphereInversionScale)
    float4 juliaC;     // (boxOffX, boxOffY, boxOffZ, w0)
    float4 rot;        // (_, _, _, fudge)
    float4 boundSphere;
};

// ===== DE region lifted verbatim from pseudokleinian4d_raymarch.metal =====
float estimateFull(float3 p, constant FoldParams& fp, thread float4& outTrap) {
    float4 z    = float4(p, fp.juliaC.w);
    float  dr   = 1.0f;
    float3 cOff = fp.juliaC.xyz;
    float4 cSize = float4(fp.boxParams.xyz, 1.0f);
    float sScale = fp.boxParams.w;
    float tube   = fp.surfParams.x, dOff = fp.surfParams.y, tweak = fp.surfParams.z, gInv = fp.surfParams.w;
    bool invert  = (fp.juliaMode == 1);
    outTrap = float4(1e20f);

    for (int i = 0; i < fp.iterations; i++) {
        if (invert) {
            float rr = max(dot(z, z), 1e-9f);
            float f = gInv / rr;
            z *= f; dr *= f;
        }
        z.xyz -= cOff * sign(z.xyz);
        z = abs(z + cSize) - abs(z - cSize) - z;
        float k = max(sScale / max(dot(z, z), 1e-9f), 1.0f);
        z *= k; dr *= k + tweak;
        float rz = length(z);
        outTrap.x = min(outTrap.x, rz);
        outTrap.y = min(outTrap.y, abs(z.x));
        outTrap.z = min(outTrap.z, length(z.xy));
        outTrap.w = min(outTrap.w, abs(rz - 1.0f));
    }

    float4 zz = z * z;
    float d1;
    if (fp.mode == 1)
        d1 = sqrt(min(min(min(zz.x+zz.y, zz.y+zz.z), zz.z+zz.w), zz.w+zz.x));
    else
        d1 = sqrt(zz.x + zz.y + zz.w);
    d1 -= tube;
    float d2 = abs(z.z);
    return 0.5f * (min(d1, d2) - dOff) / max(dr, 1e-9f);
}


float estimate(float3 p, constant FoldParams& fp) {
    float4 dummy;
    return estimateFull(p, fp, dummy);
}

bool intersectSphereForward(float3 ro, float3 rd, float3 center, float radius, thread float& tOut) {
    float3 oc = ro - center;
    float b = dot(oc, rd);
    float c = dot(oc, oc) - radius * radius;
    if (c <= 0.0f) { tOut = 0.0f; return true; }
    float disc = b * b - c;
    if (disc < 0.0f) { tOut = 0.0f; return false; }
    float sq = sqrt(disc);
    float t0 = -b - sq;
    if (t0 >= 0.0f) { tOut = t0; return true; }
    float t1 = -b + sq;
    if (t1 >= 0.0f) { tOut = t1; return true; }
    tOut = 0.0f;
    return false;
}

// ============================================================================
// Telemetry kernel — 64x36 low-res re-march, one TelemetryCell per ray
// ============================================================================

kernel void pseudokleinian4d_telemetry(
    constant FoldParams&      fp    [[buffer(0)]],
    constant TelemetryParams& tp    [[buffer(1)]],
    device   TelemetryCell*   cells [[buffer(2)]],
    uint2 gid [[thread_position_in_grid]])
{
    int px = int(gid.x);
    int py = int(gid.y);
    if (px >= tp.gridWidth || py >= tp.gridHeight) return;

    int idx = py * tp.gridWidth + px;

    float u = (float(px) + 0.5f) / float(tp.gridWidth);
    float v = 1.0f - (float(py) + 0.5f) / float(tp.gridHeight);
    float x = (2.0f * u - 1.0f) * tp.tanFov.x;
    float y = (2.0f * v - 1.0f) * tp.tanFov.y;
    float3 ro = tp.camPos.xyz;
    float3 rd = normalize(tp.camForward.xyz + x * tp.camRight.xyz + y * tp.camUp.xyz);

    float hitEps   = tp.march.x;
    float maxDist  = tp.march.y;
    float normEps  = tp.march.z;
    int   maxSteps = tp.maxSteps;
    float fudge    = fp.rot.w;

    TelemetryCell cell;
    cell.pad = 0.0f;

    float tEnter;
    if (!intersectSphereForward(ro, rd, fp.boundSphere.xyz, fp.boundSphere.w, tEnter)) {
        cell.hit = 0; cell.steps = 0; cell.depth = maxDist;
        cell.normal = float4(0.0f); cell.trap = float4(0.0f);
        cells[idx] = cell;
        return;
    }

    float t = max(0.0f, tEnter);
    bool  didHit = false;
    int   i = 0;

    for (i = 0; i < maxSteps; i++) {
        float3 p = ro + rd * t;
        float d = estimate(p, fp) * fudge;
        if (d < hitEps) { didHit = true; break; }
        t += d;
        if (t > maxDist) break;
    }

    if (!didHit) {
        cell.hit = 0; cell.steps = i; cell.depth = maxDist;
        cell.normal = float4(0.0f); cell.trap = float4(0.0f);
        cells[idx] = cell;
        return;
    }

    float3 hitPoint = ro + rd * t;

    float4 trap;
    estimateFull(hitPoint, fp, trap);

    float2 k = float2(1.0f, -1.0f);
    float3 n =
        k.xyy * estimate(hitPoint + k.xyy * normEps, fp) +
        k.yyx * estimate(hitPoint + k.yyx * normEps, fp) +
        k.yxy * estimate(hitPoint + k.yxy * normEps, fp) +
        k.xxx * estimate(hitPoint + k.xxx * normEps, fp);
    float nLen = length(n);
    float3 normal = (nLen > 1e-6f) ? n / nLen : float3(0.0f);

    cell.hit = 1; cell.steps = i; cell.depth = t;
    cell.normal = float4(normal, 0.0f); cell.trap = trap;
    cells[idx] = cell;
}
