<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Parsec.Audio</RootNamespace>
    <AssemblyName>parsec-audio</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK.Audio.OpenAL" Version="4.9.4" />
  </ItemGroup>

</Project>
