#!/usr/bin/env python3
"""Generate trimmed MIDI-only *_telemetry.metal kernels for the fractals that
lack one. Lifts each shader's FoldParams struct and DE region (helpers +
estimateFull + estimate) verbatim from <f>_raymarch.metal, then wraps them with
a fixed prologue (TelemetryParams/TelemetryCell) and the standard 64x36 march
kernel. Run from repo root; idempotent."""
import os, sys

SHADERS = os.path.join("src", "Parsec.Rendering.Metal", "Shaders")

FRACTALS = [
    "hybrid", "bicomplex", "phoenix", "biomorph", "mosely",
    "pseudokleinian4d", "riemannsphere", "mandalay", "anisotropic", "orbithybrid",
]

PROLOGUE = """#include <metal_stdlib>
using namespace metal;

// Trimmed MIDI-only telemetry kernel for {name}: one TelemetryCell per low-res
// ray (geometry stats + 4x4 cells + full-res centroid derive from this buffer on
// the CPU). No sonification wavetable/orbit-trajectory/field-scan buffers.
// GENERATED by tools/build_midi_telemetry.py from {name}_raymarch.metal — the
// FoldParams struct and DE region below are lifted verbatim. Do not hand-edit;
// re-run the generator if the DE changes.

struct TelemetryParams {{
    int   gridWidth;
    int   gridHeight;
    int   pad0;
    int   pad1;
    float4 camPos;
    float4 camForward;
    float4 camRight;
    float4 camUp;
    float4 tanFov;
    float4 march;
    int   maxSteps;
    int   pad2;
    int   pad3;
    int   pad4;
}};

struct TelemetryCell {{
    int   hit;
    int   steps;
    float depth;
    float pad;
    float4 normal;
    float4 trap;
}};

"""

INTERSECT = """bool intersectSphereForward(float3 ro, float3 rd, float3 center, float radius, thread float& tOut) {
    float3 oc = ro - center;
    float b = dot(oc, rd);
    float c = dot(oc, oc) - radius * radius;
    if (c <= 0.0f) { tOut = 0.0f; return true; }
    float disc = b * b - c;
    if (disc < 0.0f) { tOut = 0.0f; return false; }
    float sq = sqrt(disc);
    float t0 = -b - sq;
    if (t0 >= 0.0f) { tOut = t0; return true; }
    float t1 = -b + sq;
    if (t1 >= 0.0f) { tOut = t1; return true; }
    tOut = 0.0f;
    return false;
}

"""

KERNEL = """// ============================================================================
// Telemetry kernel — 64x36 low-res re-march, one TelemetryCell per ray
// ============================================================================

kernel void {name}_telemetry(
    constant FoldParams&      fp    [[buffer(0)]],
    constant TelemetryParams& tp    [[buffer(1)]],
    device   TelemetryCell*   cells [[buffer(2)]],
    uint2 gid [[thread_position_in_grid]])
{{
    int px = int(gid.x);
    int py = int(gid.y);
    if (px >= tp.gridWidth || py >= tp.gridHeight) return;

    int idx = py * tp.gridWidth + px;

    float u = (float(px) + 0.5f) / float(tp.gridWidth);
    float v = 1.0f - (float(py) + 0.5f) / float(tp.gridHeight);
    float x = (2.0f * u - 1.0f) * tp.tanFov.x;
    float y = (2.0f * v - 1.0f) * tp.tanFov.y;
    float3 ro = tp.camPos.xyz;
    float3 rd = normalize(tp.camForward.xyz + x * tp.camRight.xyz + y * tp.camUp.xyz);

    float hitEps   = tp.march.x;
    float maxDist  = tp.march.y;
    float normEps  = tp.march.z;
    int   maxSteps = tp.maxSteps;
    float fudge    = fp.rot.w;

    TelemetryCell cell;
    cell.pad = 0.0f;

    float tEnter;
    if (!intersectSphereForward(ro, rd, fp.boundSphere.xyz, fp.boundSphere.w, tEnter)) {{
        cell.hit = 0; cell.steps = 0; cell.depth = maxDist;
        cell.normal = float4(0.0f); cell.trap = float4(0.0f);
        cells[idx] = cell;
        return;
    }}

    float t = max(0.0f, tEnter);
    bool  didHit = false;
    int   i = 0;

    for (i = 0; i < maxSteps; i++) {{
        float3 p = ro + rd * t;
        float d = estimate(p, fp) * fudge;
        if (d < hitEps) {{ didHit = true; break; }}
        t += d;
        if (t > maxDist) break;
    }}

    if (!didHit) {{
        cell.hit = 0; cell.steps = i; cell.depth = maxDist;
        cell.normal = float4(0.0f); cell.trap = float4(0.0f);
        cells[idx] = cell;
        return;
    }}

    float3 hitPoint = ro + rd * t;

    float4 trap;
    estimateFull(hitPoint, fp, trap);

    float2 k = float2(1.0f, -1.0f);
    float3 n =
        k.xyy * estimate(hitPoint + k.xyy * normEps, fp) +
        k.yyx * estimate(hitPoint + k.yyx * normEps, fp) +
        k.yxy * estimate(hitPoint + k.yxy * normEps, fp) +
        k.xxx * estimate(hitPoint + k.xxx * normEps, fp);
    float nLen = length(n);
    float3 normal = (nLen > 1e-6f) ? n / nLen : float3(0.0f);

    cell.hit = 1; cell.steps = i; cell.depth = t;
    cell.normal = float4(normal, 0.0f); cell.trap = trap;
    cells[idx] = cell;
}}
"""


def extract_struct(lines, name):
    start = next(i for i, l in enumerate(lines) if l.lstrip().startswith(f"struct {name}"))
    end = next(i for i in range(start, len(lines)) if lines[i].strip() == "};")
    return start, end  # inclusive end


def build(frac):
    path = os.path.join(SHADERS, f"{frac}_raymarch.metal")
    with open(path) as fh:
        lines = fh.read().splitlines()

    fp_start, fp_end = extract_struct(lines, "FoldParams")
    fold_block = "\n".join(lines[fp_start:fp_end + 1])

    _, rp_end = extract_struct(lines, "RenderParams")
    de_start = rp_end + 1
    de_end = next(i for i in range(de_start, len(lines)) if "estimateNormal(" in lines[i])
    # trim trailing blank lines just before estimateNormal
    de_lines = lines[de_start:de_end]
    while de_lines and de_lines[0].strip() == "":
        de_lines.pop(0)
    while de_lines and de_lines[-1].strip() == "":
        de_lines.pop()
    de_block = "\n".join(de_lines)

    out = (PROLOGUE.format(name=frac)
           + fold_block + "\n\n"
           + "// ===== DE region lifted verbatim from " + frac + "_raymarch.metal =====\n"
           + de_block + "\n\n"
           + INTERSECT
           + KERNEL.format(name=frac))

    outpath = os.path.join(SHADERS, f"{frac}_telemetry.metal")
    with open(outpath, "w") as fh:
        fh.write(out)
    print(f"  wrote {outpath} ({out.count(chr(10))} lines)")


if __name__ == "__main__":
    targets = sys.argv[1:] or FRACTALS
    for frac in targets:
        build(frac)
